version: "2"
services:
  redis:
    image: redis:alpine

  fluentd:
    image: ruby:2.4-alpine3.6
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    working_dir: /app
    environment:
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - redis
      - sidekiq
    command: ["sh", "./run_fluentd.sh"]

  test:
    image: ruby:2.4-alpine3.6
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    working_dir: /app
    environment:
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - redis
      - sidekiq
    command: ["sh", "./run.sh"]

  sidekiq:
    build:
      context: .
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    working_dir: /app
    depends_on:
      - redis
    environment:
      REDIS_URL: "redis://redis:6379"
    command: ["sh", "./run_sidekiq.sh"]


volumes:
  bundle:
    driver: local
